# Data Analysis Numpy & CSV's

## Tasks Today:

1) <b>Numpy</b> <br>
 &nbsp;&nbsp;&nbsp;&nbsp; a) Python List Comparison <br>
 &nbsp;&nbsp;&nbsp;&nbsp; b) In-Class Exercise #1 <br>
 &nbsp;&nbsp;&nbsp;&nbsp; c) Importing <br>
 &nbsp;&nbsp;&nbsp;&nbsp; d) Creating an NDArray <br>
 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; - np.array() <br>
 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; - np.zeros() <br>
 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; - np.ones() <br>
 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; - np.arange() <br>
 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; - Making Lists into NDArrays <br>
 &nbsp;&nbsp;&nbsp;&nbsp; e) Performing Calculations on NDArrays <br>
 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; - Summation <br>
 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; - Difference <br>
 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; - Multiplication <br>
 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; - Division <br>
 &nbsp;&nbsp;&nbsp;&nbsp; f) Numpy Subsetting <br>
 &nbsp;&nbsp;&nbsp;&nbsp; g) Multi-dimensional Arrays <br>
 &nbsp;&nbsp;&nbsp;&nbsp; h) Indexing NDArrays <br>
 &nbsp;&nbsp;&nbsp;&nbsp; i) Checking NDArray Type <br>
 &nbsp;&nbsp;&nbsp;&nbsp; j) Altering NDArray Type <br>
 &nbsp;&nbsp;&nbsp;&nbsp; k) Checking the Shape <br>
 &nbsp;&nbsp;&nbsp;&nbsp; l) Altering the Shape <br>
 &nbsp;&nbsp;&nbsp;&nbsp; m) In-Class Exercise #2 <br>
 &nbsp;&nbsp;&nbsp;&nbsp; n) Complex Indexing & Assigning <br>
 &nbsp;&nbsp;&nbsp;&nbsp; o) Elementwise Multplication <br>
 &nbsp;&nbsp;&nbsp;&nbsp; p) np.where() <br>
 &nbsp;&nbsp;&nbsp;&nbsp; q) Random Sampling <br>

2) <b>Working With CSV's</b> <br>
 &nbsp;&nbsp;&nbsp;&nbsp; a) Imports <br>
 &nbsp;&nbsp;&nbsp;&nbsp; b) Reading a CSV <br>
 &nbsp;&nbsp;&nbsp;&nbsp; c) Loading a CSV's Data <br>
 &nbsp;&nbsp;&nbsp;&nbsp; d) Checking Number of Records <br>
 
3) <b>Exercises</b> <br>
 &nbsp;&nbsp;&nbsp;&nbsp; a) #1 - Calculate BMI with NDArrays <br>
 &nbsp;&nbsp;&nbsp;&nbsp; b) #2 - Find the Average Sum of Marathon Runners <br>
 &nbsp;&nbsp;&nbsp;&nbsp; c) #3 - Random Matrix Function <br>
 &nbsp;&nbsp;&nbsp;&nbsp; d) #4 - Comparing Boston Red Sox Hitting Numbers <br>

## Numpy <br>

<p>NumPy is a library for the Python programming language, adding support for large, multi-dimensional arrays and matrices, along with a large collection of high-level mathematical functions to operate on these arrays.</p>
<ul>
    <li>Shape = Rows & Columns</li>
    <li>Matrix = Entire Array</li>
    <li>Vector = Variables to be applied (same vector as the one used in physics)</li>
    <li>Array = Similar to lists</li>
</ul>

#### Python List Comparison

<p>Lists are flexible, dynamic python objects that do their job quite well. But they do not support some mathematical operations in an intuitive way. Consider the summation of two lists, $l_1$ and $l_2$</p>

In [7]:
# create two lists and sum both of them together (results may not be what you expect)
l_1 = [1,2,3]
l_2 = [4,5,6]

print(f'Sum of {l_1} + {l_2} using python operators in one line: {l_1 + l_2}')

Sum of [1, 2, 3] + [4, 5, 6] using python operators in one line: [1, 2, 3, 4, 5, 6]


<p>If we wanted to sum lists elementwise, we could write our own function that does the job entirely within the framework of python</p>

#### In-Class Exercise #1 - Write a function that sums the indexes of two lists <br>
<p>Ex: [2, 3, 4] + [1, 5, 2] = [3, 8, 6]</p>

In [11]:
def listSum(list_1, list_2):
    list_3 = []
    for i in range(len(list_1)):
        list_3.append(list_1[i] + list_2[i])
    return list_3

l_1 = [2,3,4]
l_2 = [1,5,2]
listSum(l_1, l_2)

[3, 8, 6]

#### Importing

In [3]:
# always import as np, standard across all of data science/analysis
import numpy as np

#### Creating an NDArray <br>
<p>NumPy is based around a class called the $\textit{NDArray}$, which is a flexible vector / matrix class that implements the intuitive matrix and vector arithmatic lacking in basic Python. Let's start by creating some NDArrays:</p>

###### - np.array()

In [15]:
arr_1 = [0,1,2,3]

new_arr = np.array(arr_1)

print(arr_1)
print(new_arr)

[0, 1, 2, 3]
[0 1 2 3]


###### - np.zeros()

In [16]:
# Shape -- np.zeros() has a parameter of "shape" that must be given
arr_zeros = np.zeros((3,3))
arr_zeros

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

###### - np.ones()

In [18]:
arr_ones = np.ones((3,3), int)
arr_ones_flt = np.ones((3,3))
arr_ones
# arr_ones_flt

# notice no dots after the numbers, because we specified the datatype to be integer

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

###### - np.arange()

In [19]:
arr_range = np.arange(1,20)
arr_range

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

###### - Making Lists into NDArrays

In [22]:
some_list = [99,14,7]
numpy_array = np.array(some_list)
numpy_array

array([99, 14,  7])

#### Performing Calculations on NDArrays

###### - Summation

In [24]:
# when doing operations on arrays, make sure the arrays are the same length, or "shape" according to numpy
np_list = np.array([5,10,15,20,25,30])
np_list_2 = np.array([10,20,30,40,50,60])
    
result_sum = np_list + np_list_2
result_sum

array([15, 30, 45, 60, 75, 90])

###### - Difference

In [25]:
result_diff = np_list_2 - np_list
result_diff

array([ 5, 10, 15, 20, 25, 30])

###### - Multiplication

In [26]:
result_prod = np_list * np_list_2
result_prod

array([  50,  200,  450,  800, 1250, 1800])

###### - Division

In [27]:
result_div = np_list/np_list_2
result_div

array([0.5, 0.5, 0.5, 0.5, 0.5, 0.5])

#### Modulo

In [31]:
result_mod = np_list % np_list_2
result_mod

array([ 5, 10, 15, 20, 25, 30])

#### Floor Division

In [34]:
result_floor = np_list // np_list_2
result_floor

array([0, 0, 0, 0, 0, 0])

#### Numpy Subsetting

In [4]:
# print(result_prod)
# print(result_prod<=800) # returns boolean value based on the comparison

test_ndStrings = np.array(['Bob','Mark','Angelica','Barb'])
print(test_ndStrings[test_ndStrings == 'Bob'])

# test_nums = np.array([1,2,3,4,5])
# new_nums = test_nums[test_nums < 5]
# print(new_nums)

# conditioal check, returns true or false
# print(arr1 < 2)
# print(arr2 >= 2)

# conditional check, that returns the elements that meet the given condition


['Bob']


In [5]:
new = np.array([name for name in test_ndStrings if name[0] == 'B'])
new

array(['Bob', 'Barb'], dtype='<U4')

#### Multi-dimensional Arrays <br>
<p>NumPy seamlessly supports multidimensional arrays and matrices of arbitrary dimension without nesting NDArrays. NDArrays themselves are flexible and extensible and may be defined with such dimensions, with a rich API of common functions to facilitate their use. Let's start by building a two dimensional 3x3 matrix by conversion from a nested group of core python lists $M = [l_0, l_1, l_2]$:</p>

In [9]:
# a matrix is, essentially, a list full of lists

aList = [0,1,2]
bList = [3,4,5]
cList = [6,7,8]

# first step: convert lists into a Matrix
M = [aList, bList, cList]
print(M)
print(M[2][0])

# second step: place Matrix inside NDArray
ND_M = np.array(M)
ND_M

[[0, 1, 2], [3, 4, 5], [6, 7, 8]]
6


array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### Indexing NDArrays <br>
<p> Similar to lists within lists; however, the syntax looks more like C programming language.... It is [1, 2] to access the second row, third element.</p>

In [10]:
# in order to grab an item from a matrix, locate the row and column it sits in
# numbering is the same as the index numbers we are comfortable with 
# to get 6 from the above array, we want to access row 2 (the third row, since the first row is 0), column 0s
ND_M[2,0]

6

#### Assigning Values in NDArrays

In [13]:
ND_M[2,0] = 10
ND_M

ND_M[2,0] = 8
ND_M

array([[0, 1, 2],
       [3, 4, 5],
       [8, 7, 8]])

<p>Notice above how we ended up with a 1 in the target element's place. This is a data type issue. The .dtype() method is supported by all NDArrays, as well as the .astype() method for casting between data types:</p>

#### Checking NDArray Type

In [15]:
# usind the .dtype() method
nd_type = ND_M.dtype
ND_M.dtype


dtype('int64')

#### Altering NDArray Type

In [18]:
print(nd_type)

changed = ND_M.astype(np.float32)
changed.dtype
changed

int64


array([[0., 1., 2.],
       [3., 4., 5.],
       [8., 7., 8.]], dtype=float32)

In [ ]:
# Checking the Shape of the ND_M Numpy Array
# Using the method .shape


#### Checking the Shape <br>
<p>The behavior and properties of an NDArray are often sensitively dependent on the $\textit{shape}$ of the NDArray itself. The shape of an array can be found by calling the .shape method, which will return a tuple containing the array's dimensions:</p>

In [20]:
 # shape is always rows x columns
# Checking the Shape of the ND_M Numpy Array
# Using the method .shape

changed.shape
ND_M.shape

# print(type(result_changed.shape))

(3, 3)

#### Altering the Shape <br>
<p>As long as the number of elements remains fixed, we can reshape NDArrays at will:</p>

In [29]:
# Change the shape of the numpy array
# Using the method .reshape()

# The reshape should be a multiple of the original shape
# Meaning we can have a shape of (1,9) or (9,1) or (3,3)
# creates a copy of the original, it does not actually change the original

print(ND_M)

# (9,1) == 9 rows , 1 column
new=ND_M.reshape(9,1)
print(ND_M)
print(new)


[[0 1 2]
 [3 4 5]
 [8 7 8]]
[[0 1 2]
 [3 4 5]
 [8 7 8]]
[[0]
 [1]
 [2]
 [3]
 [4]
 [5]
 [8]
 [7]
 [8]]


In [ ]:
# keep in mind that the shape numbers do matter, (9, 1) is different than (1, 9)



#### In-Class Exercise #2 - Create a matrix of range 0 up to 16 and reshape it into a 4x4 matrice

In [37]:
"""
OUTPUT
    array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])
"""
new_range = np.arange(16).reshape(4,4)
new_range



array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

#### Complex Indexing & Assinging

In [79]:
M2 = np.zeros((6,6),int)

# Set every first element in each row to 1
M2[:,0] = 1
print("\n",M2)

# Set all elements in axis 3 to 5 (Excluding 5) to be equal to the number 5
M2[3:5,:] = 5
print("\n",M2)

# reset the matrix back to 0
M2 = M2 * 0
print("\n",M2)


# Set the second and third columns to a number == 2
M2[:,2:4] = 2
M2



# Creating a vector in numpy -- vector is a list
x = np.arange(6)
print(x)


# Reset the Matrix to 0
M2 = M2 * 0
print("\n", M2)


# Set the first row to that range of vector numbers we just created
M2[:,0] = x
print("\n", M2)



#################
# M[rows,columns]
#################


 [[1 0 0 0 0 0]
 [1 0 0 0 0 0]
 [1 0 0 0 0 0]
 [1 0 0 0 0 0]
 [1 0 0 0 0 0]
 [1 0 0 0 0 0]]

 [[1 0 0 0 0 0]
 [1 0 0 0 0 0]
 [1 0 0 0 0 0]
 [5 5 5 5 5 5]
 [5 5 5 5 5 5]
 [1 0 0 0 0 0]]

 [[0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]]
[0 1 2 3 4 5]

 [[0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]]

 [[0 0 0 0 0 0]
 [1 0 0 0 0 0]
 [2 0 0 0 0 0]
 [3 0 0 0 0 0]
 [4 0 0 0 0 0]
 [5 0 0 0 0 0]]


#### Elementwise Multiplication

<p>As long as the shapes of NDArrays are 'compatible', they can be multiplied elementwise, broadcasted, used in inner products, and much much more. 'Compatible' in this context can mean compatible in the linear algebraic sense, i.e. for inner products and other matrix multiplication, or simply sharing a dimension in such a manner that broadcasting 'makes sense'. Here are some examples of this:</p>

In [80]:
# Initialize a vector of range 6, then reset Matrix to zero and run vector multiplication on the matrix
v = M2[:,:]
v = v*0
print(M2)
print(v)

#change bottom row to be full of 2's
v[-1:,:] = 2
print(v)
new_M = M2*v
print(new_M)


# Reset the Matrix to 0


[[0 0 0 0 0 0]
 [1 0 0 0 0 0]
 [2 0 0 0 0 0]
 [3 0 0 0 0 0]
 [4 0 0 0 0 0]
 [5 0 0 0 0 0]]
[[0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]]
[[0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [2 2 2 2 2 2]]
[[ 0  0  0  0  0  0]
 [ 0  0  0  0  0  0]
 [ 0  0  0  0  0  0]
 [ 0  0  0  0  0  0]
 [ 0  0  0  0  0  0]
 [10  0  0  0  0  0]]


#### np.where() <br>
<p>If statement within NDArrays that allows you to run conditionals on the entire array</p>

In [86]:
new_arr = np.array([400,500,600,700])
print(new_arr)
print(np.where(new_arr < 600))

# Transform Data based on boolean mask == True
new_arr[np.where(new_arr < 600)] == 400

#subsetting syntax
print(new_arr[new_arr < 600] == 400)
print(new_arr)

[400 500 600 700]
(array([0, 1]),)
[ True False]
[400 500 600 700]


#### Random Sampling <br>
<p>NumPy provides machinery to work with random numbers - something often needed in a broad spectrum of data science applications.</p>

In [105]:
# np.random.uniform()
#np.random.randint() displays random integers within the given parameters

# A single call generates a single random number between 0 and 1

print('Here is a random number: %s' % np.random.uniform())

# You can also pass some parameters or bounds

print('Here is a random number between 0 and 1 Million: %s' % np.random.uniform(0, 1e6))

# You can also generate a bunch of random numbers all at once

print('Here are 5 random numbers between 0 and 10: %s' % np.random.uniform(0, 10, 5))

# Even matrices with shapes as a parameter

print('Here is a 5x5 matrix with numbers between 0 and 10: \n %s' % np.random.randint(0, 100, (5, 5)))
print('Here is a 1x6 matrix with numbers between 1 and 64: \n %s' % np.random.randint(0,64, (1, 6)))

Here is a random number: 0.25946787222971945
Here is a random number between 0 and 1 Million: 23079.779344908457
Here are 5 random numbers between 0 and 10: [4.29769451 6.3656122  9.95757632 1.79730422 0.62598159]
Here is a 5x5 matrix with numbers between 0 and 10: 
 [[75 47 73 87 75]
 [18 53 30  6 13]
 [24 40 81  9 77]
 [45 31 70 51  1]
 [76 79 18 72  4]]
Here is a 1x6 matrix with numbers between 1 and 64: 
 [[23 13 40 54 15 58]]


## Working With CSV's

#### Imports

In [106]:
import csv
import numpy as np
from datetime import datetime

#### Reading a CSV

In [ ]:
# Creating Function to open and read CSV data
def open_csv(filepath, d = ','):
    # instantiate an empty dataset
    data = []
    with open(filepath, encoding = 'utf-8') as myData:
        #use csv reader to read filepath into python
        info = csv.reader(myData, delimiter = d, )
        print(info)
        # Loop over information and append to data
        for row in info:
            data.append(row)
    return data

# use our function to open marathon 2017
csv_data=open_csv("../files/boston_marathon2017_edited.csv")
csv_data[1:5]



#### Loading a CSV's Data 

In [ ]:
FIELDS = ['Rk', 'Pos', 'Name', 'Age', 'G', 'PA', 'AB', 'R', 'H', '2B', '3B', 'HR', 'RBI', 'SB', 'CS', 
          'BB', 'SO', 'BA', 'OBP', 'SLG', 'OPS', 'OPS+', 'TB', 'GDP', 'HBP', 'SH', 'SF', 'IBB']

# i = integer, f = float, |s25 = string with 25 characters
DATATYPES = [('rk', 'i'), ('pos', '|S25'), ('name', '|S25'), ('age', 'i'), ('g', 'i'), ('pa', 'i'), ('ab', 'i'),
                ('r', 'i'), ('h', 'i'), ('2b', 'i'), ('3b', 'i'), ('hr', 'i'), ('rbi', 'i'), ('sb', 'i'), ('cs', 'i'),
                ('bb', 'i'), ('so', 'i'), ('ba', 'f'), ('obp', 'f'), ('slg', 'f'), ('ops', 'f'), ('opsp', 'i'),
                ('tb', 'i'), ('gdp', 'i'), ('hbp', 'i'), ('sh', 'i'), ('sf', 'i'), ('ibb', 'i')]

# instead of loading csv normally, let's load it into a numpy array to calculate results on

def load_data(filepath, d = ','):
    data = np.genfromtxt(filepath, delimiter = d, skip_header = 1,
                        usecols = np.arange(0,23), invalid_raise = False, 
                        names = FIELDS, dtype = DATATYPES)
    return data

bs2017 = load_data('../files/redsox_2017_hitting.txt')
names = bs2017["Name"]
rank = bs2017["Rk"]
age = bs2017["Age"]
hits = bs2017["H"]

# for i in range(len(names)):
#     print(f"{names[i]} had {hits[i]} hits.")

new_arr = bs2017["Name"]
np.append(new_arr, hits, axis=0)

#### Summing the top 5 hitters for HR's

In [ ]:
# find the top 5 hr hitters

# Step 1: Get all HR data into a variable
# Step 2: Get all Player Names
# Step 3: Create new list for new_names (empty to start)
# Step 4: Decode the player names into regular strings
# Step 5: Grab all data and place inside of a zipped list
# Step 6: Sort values based on HR data

# Step 1
homeruns = bs2017["HR"]

# Step 2
names = bs2017["Name"]

# Step 3
new_names = []

# Step 4
for name in names:
    new_names.append(name.decode('utf-8'))

# print(new_names)

# Step 5
zipped_values=[]
for i in range(len(new_names)):
    zipped_values.append((new_names[i], homeruns[i]))

print(zipped_values)

# Step 6
top_five = sorted(zipped_values, key = lambda x: x[1], reverse=True)
top_five[0:5]

# Exercises To Complete.... <br>
<p>Given in separate file after completion of this file</p>

### Q1: BMI Calculation

In [137]:
import numpy as np
# formula = weight / (height**2) * 730
height = [69, 70, 71, 72, 73, 74, 75]
weight = [110, 120, 130, 140, 150, 160, 170]

# OUTPUT: [16.86620458 17.87755102 18.82562984 19.71450617 20.54794521 21.32943755
# 22.06222222]

np_height = np.array(height)
np_weight = np.array(weight)

bmi = np.array((np_weight / (np_height**2)) * 730)
bmi

array([16.86620458, 17.87755102, 18.82562984, 19.71450617, 20.54794521,
       21.32943755, 22.06222222])

### #2 - Create a function that will take in two parameters and will create a random matrix based off of those parameters. Extra: Have additional parameters taken in that allow the user to choose the shape and data type of the matrix.

In [164]:
"""
Example Result
array([[14.21633515,  7.98846653,  9.64140715],
       [ 6.30982234,  9.96414331,  8.43153688],
       [14.73102068, 11.76072894, 14.23356121]])
"""
#output is result = np.array(something)
# assign variables that will be parameters as random.randint

def makeMatrix(low,high):
    num_of_nums = np.random.randint(low,high)
    array_1 = np.random.uniform(low, high, num_of_nums)
    array_2 = np.random.uniform(low, high, num_of_nums)
    array_3 = np.random.uniform(low, high, num_of_nums)
    mat_1 = [array_1, array_2, array_3]
    return mat_1

makeMatrix(1,10)

[array([7.04935107, 3.54488355, 3.55950055, 7.78490706]),
 array([7.01350969, 6.9404076 , 5.27892825, 6.15953424]),
 array([7.68275844, 3.82338993, 9.50395685, 8.66571802])]

### #3 - Extra: Open and load the data in the two text files that have the Boston Red Sox hitting data for the past seasons. Compare the difference in the two years by putting the data into an NDArray and running a differencial operation on it. The column to look for will be SLG.

Your output should display which year (either 2017 or 2018) was a better year based on SLG

In [174]:
"""
Example Result - Not the actual result
Boston 18 had more SLG in 2018
[0.404 0.443 0.392 0.403 0.482 0.424 0.402 0.459 0.429 0.354 0.387 0.333
 0.539 0.243 0.262 0.354 0.342 0.339 0.328 0.306 0.222 0.2   1.   ]
"""

FIELDS = ['Rk', 'Pos', 'Name', 'Age', 'G', 'PA', 'AB', 'R', 'H', '2B', '3B', 'HR', 'RBI', 'SB', 'CS', 
          'BB', 'SO', 'BA', 'OBP', 'SLG', 'OPS', 'OPS+', 'TB', 'GDP', 'HBP', 'SH', 'SF', 'IBB']

DATATYPES = [('rk', 'i'), ('pos', '|S25'), ('name', '|S25'), ('age', 'i'), ('g', 'i'), ('pa', 'i'), ('ab', 'i'),
                ('r', 'i'), ('h', 'i'), ('2b', 'i'), ('3b', 'i'), ('hr', 'i'), ('rbi', 'i'), ('sb', 'i'), ('cs', 'i'),
                ('bb', 'i'), ('so', 'i'), ('ba', 'f'), ('obp', 'f'), ('slg', 'f'), ('ops', 'f'), ('opsp', 'i'),
                ('tb', 'i'), ('gdp', 'i'), ('hbp', 'i'), ('sh', 'i'), ('sf', 'i'), ('ibb', 'i')]

#Use this function to actually open the data inside of a NDArray

def rs_data(filepath, d = ','):
    data = np.genfromtxt(filepath, delimiter = d, skip_header = 1,
                        usecols = np.arange(0,23), invalid_raise = False, 
                        names = FIELDS, dtype = DATATYPES)
    return data

def better_slugging():
    bs2018 = rs_data('../files/redsox_2018_hitting.txt')
    bs2017 = rs_data('../files/redsox_2017_hitting.txt')
    slugging18 = np.mean(bs2018["SLG"])
    slugging17 = np.mean(bs2017["SLG"])
    
    if slugging17 > slugging18:
        return f'Boston had better slugging in 2017. Avg slg % was {slugging17} compared to {slugging18}'
    else:
        return f'Boston had better slugging in 2018. Avg slg % was {slugging18} compared to {slugging17}'

better_slugging()
    

'Boston had better slugging in 2017. Avg slg % was 0.393347829580307 compared to 0.38749998807907104'